### ISSUE TITLE
Social Website links

### ISSUE THREAD

**Issue by GianCastle** [React-Dominicana/dominicans-who-code-react#1]
As a user, I want the CodersCards component to display social link icons as shown in the original Dominican Who Code App

![image](https://user-images.githubusercontent.com/6842883/64492350-0c257780-d241-11e9-809f-7572a8a77265.png)

AC:
- If the user dont provide any of the  social links, then the icon will not be rendered

**Comment by jpozo20** [comment]
Which icon font will we be using? Font-Awesome? Glyphicons?

**Comment by GianCastle** [comment]
Nice question, @jpozo20 
Since the original website use Font Awesome as an icon library, we need to use those ones as well!

Cheers!

**Comment by GianCastle** [comment]
Hey, @mecm1993  could you please make a comment on this issue?
So then, I can assign you this issue before checking out your PR?

**Comment by mecm1993** [comment]
> Hey, @mecm1993 could you please make a comment on this issue?
> So then, I can assign you this issue before checking out your PR?

Sure.

**Comment by GianCastle** [comment]
This was merged from my fork branch. So I'll close this issue
