### ISSUE TITLE
Refactor file structure

### ISSUE THREAD

**Issue by GianCastle** [React-Dominicana/dominicans-who-code-react#3]
Actually, the components are living on [component_name]/index.js file. This make the debugging process a bit tedious. Since all the components files called the same and in the console will display the same name over and over again.

AC:
All components folders must have
- A file with this naming convention [C_NAME].js
- A index.js file (so that, we can import it on our source code more easily)

**Comment by jpozo20** [comment]
I think you mean the js file must be [component_name].js, just like the folder.

But I don't understand the thing with the index.js. 
Why does each component need an index.js file?

**Comment by GianCastle** [comment]
That's a nice question, bro. @jpozo20 

With an index.js file on every folder you can save some typing whenever you need to import some component. Consider this example without having an index file

```
import Component from './components/foo/foo'
```
You need to specify the file each time you need to import the component. However, if you have an index file on each folder you can save those last typings on your import like I show you below...

```
import Component from './components/component/foo
```

Since Node will look for an index.js file when resolving an import path, a path to `./component/foo` is really a path to ./component/foo/index.js which is a file that points to the actual component file.

**Comment by jpozo20** [comment]
Nice, thanks for the explanation. Makes sense. 
Although it may be because I'm spoiled by the React tutorial, but I prefer to name each file as the component should be named. 

But let's wait and see what the other coders say.

**Comment by GianCastle** [comment]
@HarysVizcaino  @amaurygomez  could you please take a look into this.

**Comment by amaurygomez** [comment]
I usually use the name of the folder with the name of the component and in the index.js declaring the path. Although lately I have tried using .jsx for some warnings and errors of visual studio.

**Comment by Jose4gg** [comment]
I think we should ban default exports too, 

Here is my argument: https://blog.neufund.org/why-we-have-banned-default-exports-and-you-should-do-the-same-d51fdc2cf2ad

**Comment by jpozo20** [comment]
@Jose4gg that makes sense for modules where you have many functions. I don't see the benefits on components since you mostly use the component for rendering, not for using its methods (which should be internal to it).

**Comment by jpozo20** [comment]
@GianCastle @amaurygomez I still don't like, but if you guys say it's better then that's the way to go. 😄

**Comment by Jose4gg** [comment]
@jpozo20 Yep, but if we are going with the index.js strategy, we will need to name the exports at some point, I think it would be ideal to maintain consistency over the files.

**Comment by GianCastle** [comment]
Thanks for the post @Jose4gg 

I love to maintain my bundle sizes smaller as possible. The treeshaking support convinces me a lot! 

Let's change it
@jpozo20  Will you address this issue?

**Comment by GianCastle** [comment]
As I see this issue is inactive, I'll take it at 6:00 p.m.

@jpozo20
